services:
  vault:
    build:
      context: ./
      dockerfile: infra/vault/Dockerfile
    container_name: vault
    cap_add:
      - IPC_LOCK
    user: root
    expose:
      - "${VAULT_PORT}"
    entrypoint: ["sh", "/vault/scripts/entrypoint.sh"]
    volumes:
      - ./infra/vault/config/vault.hcl:/vault/config/vault.hcl:ro
      - ./infra/vault/scripts:/vault/scripts:ro
      - ./infra/vault/data:/vault/data
    environment:
      - VAULT_ADDR=http://vault:${VAULT_PORT}
      - VAULT_API_ADDR=http://vault:${VAULT_PORT}
      - VAULT_CLUSTER_ADDR=https://vault:8201
    healthcheck:
      test: ["CMD-SHELL", "vault status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: on-failure:10
    networks:
      - app-network

  vault-agent:
    build:
      context: ./
      dockerfile: infra/vault/Dockerfile
    container_name: vault-agent
    user: root
    cap_add:
      - IPC_LOCK
    depends_on:
      - vault
    volumes:
      - ./infra/vault/data:/vault/data
      - ./infra/vault/config/agent.hcl:/vault/config/agent.hcl:ro
    environment:
      - VAULT_ADDR=http://vault:${VAULT_PORT}
    command: agent -config=/vault/config/agent.hcl
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    user: ${POSTGRES_USER}
    ports:
      - "5433:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mapping:
    build:
      context: ./
      dockerfile: mapping/Dockerfile
    hostname: ${MAPPING_HOST}
    ports:
      - "${MAPPING_PORT}:${MAPPING_PORT}"
    container_name: mapping
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  mapping_cleaner:
    build:
      context: ./
      dockerfile: mapping_cleaner/Dockerfile
    container_name: mapping_cleaner
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  auth:
    build:
      context: ./
      dockerfile: auth_service/Dockerfile
    hostname: ${AUTH_SERVICE_HOST}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    container_name: auth
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  tokenizer:
    build:
      context: ./
      dockerfile: tokenizer/Dockerfile
    hostname: ${TOKENIZER_HOST}
    ports:
      - "${TOKENIZER_PORT}:${TOKENIZER_PORT}"
    container_name: tokenizer
    depends_on:
      - vault-agent
    networks:
      - app-network

  gateway:
    build:
      context: ./
      dockerfile: gateway/Dockerfile
    hostname: ${GATEWAY_HOST}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    container_name: gateway
    depends_on:
      - tokenizer
      - mapping
      - auth
    networks:
      - app-network

volumes:
  go-mod-cache:
  go-build-cache:
  postgres_data:
  redis_data:

networks:
  app-network:
